### ISSUE TITLE
Tunarr image error

### ISSUE THREAD

**Issue by chrisbenincasa** [nwithan8/unraid_templates#37]
Hey! Somebody just reported this in our discord. Not sure what the deal is...latest tag exists in both docker repos. 

![image](https://github.com/user-attachments/assets/3da4d347-10b4-4348-9dda-d72573b9166f)

**Comment by DingoAU** [comment]
I was the user in Discord.
When running the FixCommonProblems plugin, this is one of the warnings that spits out.
I only setup Tunarr last night, doubt this has a factor in this message though.
![image](https://github.com/user-attachments/assets/caa7bedd-d841-4228-9dac-9b72c16fb576)
It still shows on the Community Apps list. Maintainer appears to be https://github.com/nwithan8/unraid_templates

**Comment by nwithan8** [comment]
That was an old warning, triggered from before Tunarr had a `latest` tag and therefore the Unraid template was invalid. Tunarr, at least on my end, is no longer blacklisted and is available in the Community Apps store. That user may need to update their CA plugin accordingly to reflect the changes.

**Comment by chrisbenincasa** [comment]
Thanks for the update!

**Comment by DingoAU** [comment]
I was the discord user. Just checked the CA plugin, no updates available currently. It does still show on the CA store though strangely.
