### ISSUE TITLE
templates/christmas_community.xml - Setup Issue

### ISSUE THREAD

**Issue by kfoxton** [nwithan8/unraid_templates#38]
As per here [https://github.com/Wingysam/Christmas-Community/issues/136](https://github.com/Wingysam/Christmas-Community/issues/136)

The DB path should be under /data/dbs so that is lasts though docker restarts
For the innitial startup the login failure redirect should go to /setup, and there should be a note to change it to /login after the admin user is created.

Thanks!

**Comment by nwithan8** [comment]
Pushing out an update now, thanks for the heads up!
