### ISSUE TITLE
Maybe image docker, how to connect BDD ?

### ISSUE THREAD

**Issue by thymon13** [nwithan8/unraid_templates#39]
Hello,

Is this the right method ?
<img width="819" alt="image" src="https://github.com/user-attachments/assets/caec1931-2bab-4425-be30-6e9ad35fc93e">

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/76c2adbe-b530-429f-83c8-2c35d8b93ba9">

Thank you for your help

**Comment by nwithan8** [comment]
Just IP address. Port is added in "Postgres - Port"
