### ISSUE TITLE
Postiz app is actually the Gitroom app on Unraid

### ISSUE THREAD

**Issue by freestonefrank** [nwithan8/unraid_templates#49]
<img width="671" alt="Screenshot 2024-11-17 at 6 19 17 PM" src="https://github.com/user-attachments/assets/214b6bac-6c2e-4917-b0c0-d5288eccbbd2">
I downloaded and installed this

and this is what my homepage shows

<img width="1424" alt="Screenshot 2024-11-17 at 6 06 01 PM" src="https://github.com/user-attachments/assets/a311c828-3117-4cf4-9b3b-2c437fd886a6">

**Comment by nwithan8** [comment]
Closes via https://github.com/gitroomhq/postiz-app/issues/438, which was closed via a Discord message:

> Please pass the IS_GENERAL="true" variable

This is mapped to "Is Self-Hosted" under Advanced settings, which should default to `true`: https://github.com/nwithan8/unraid_templates/blob/fc911169c3ea3ad21c7eeee60e4c3a7327b0993e/templates/postiz.xml#L83

**Comment by matthiscock** [comment]
Re-opening

Installed today on unraid
set IS_GENERAL to true
Still getting Gitroom

**Comment by nwithan8** [comment]
> On save, it doesnt look like the IS_GENERAL variable is being compiled / set in the save screen

Can you clarify what you mean by this?
